# -*- coding: utf-8 -*-
"""
Created on Wed Jul  6 19:28:37 2011

@author: steven
"""

# project euler problem ID 2
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not 
# exceed four million, find the sum of the even-valued terms.

def fibo(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibo(n - 1) + fibo(n - 2)

def control():
    i = 0
    total = 0
    while fibo(i) < 4000000:
        if fibo(i) % 2 == 0:
            total += fibo(i)
        i += 1
    print total

control()

# real    0m16.848s
# user    0m16.841s
# sys     0m0.008s